pref("extensions.torbirdy.protected", false);
pref("extensions.torbirdy.proxy", 0);
pref("extensions.torbirdy.first_run", true);
pref("extensions.torbirdy.warn", true);
pref("extensions.torbirdy.startup_folder", false);
pref("extensions.torbirdy.enigmail.throwkeyid", true);
pref("extensions.torbirdy.enigmail.confirmemail", false);
pref("extensions.torbirdy.timezone", true);
pref("extensions.torbirdy.whonix_run", true);
